
scrape_configs:
  - job_name: 'api_gateway_metrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    scheme: https
    tls_config:
      insecure_skip_verify: true
    oauth2:
      client_id: 'metrics'
      client_secret: '6ZJFi6udExYt7BUq9gjuDul1CzQxnxM4'
      token_url: 'http://172.17.0.1:9090/realms/food-delivery-app/protocol/openid-connect/token'
    static_configs:
      - targets: ['172.17.0.1:8080']
        labels:
          app: 'food-delivery-app-metrics'
  - job_name: 'order_command_metrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: [ '172.17.0.1:8181' ]
        labels:
          app: 'food-delivery-app-metrics'
  - job_name: 'restaurant_service_metrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: [ '172.17.0.1:8183' ]
        labels:
          app: 'food-delivery-app-metrics'