
scrape_configs:
  - job_name: 'api_gateway_metrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    scheme: https
    static_configs:
      - targets: ['0.0.0.0:8080']
        labels:
          app: 'food-delivery-app-metrics'