
version: '3.7'

services:
  postgres:
    image: debezium/postgres:16
    platform: linux/amd64
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
    command:
      - "postgres"
      - "-c"
      - "max_connections=200"
      - "-c"
      - "max_replication_slots=10"
      - "-c"
      - "max_wal_senders=10"
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    platform: linux/amd64
    container_name: keycloak
    depends_on:
      - postgres
    ports:
      - "9090:8080"
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB_URL: jdbc:postgresql://postgres:5432/postgres
      KC_DB: "postgres"
      KC_DB_USERNAME: user
      KC_DB_PASSWORD: admin
  kafka-broker-1:
    image: confluentinc/cp-kafka:latest
    platform: linux/amd64
    container_name: kafka-broker-1
    ports:
      - "19092:19092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: CONTROLLER://kafka-broker-1:9093,BROKER://kafka-broker-1:9092
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka-broker-1:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-broker-1:9093,2@kafka-broker-2:9093,3@kafka-broker-3:9093'
      CLUSTER_ID: f1p7ULGbT_qGDINRRLoz7g
  kafka-broker-2:
    image: confluentinc/cp-kafka:latest
    platform: linux/amd64
    container_name: kafka-broker-2
    ports:
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: CONTROLLER://kafka-broker-2:9093,BROKER://kafka-broker-2:9092
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka-broker-2:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: BROKER:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-broker-1:9093,2@kafka-broker-2:9093,3@kafka-broker-3:9093'
      CLUSTER_ID: f1p7ULGbT_qGDINRRLoz7g
  kafka-broker-3:
    image: confluentinc/cp-kafka:latest
    platform: linux/amd64
    container_name: kafka-broker-3
    ports:
      - "39092:39092"
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: CONTROLLER://kafka-broker-3:9093,BROKER://kafka-broker-3:9092
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka-broker-3:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: BROKER:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-broker-1:9093,2@kafka-broker-2:9093,3@kafka-broker-3:9093'
      CLUSTER_ID: f1p7ULGbT_qGDINRRLoz7g
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    platform: linux/amd64
    container_name: kafka-ui
    ports:
      - "9000:8080"
    depends_on:
      - kafka-broker-1
      - kafka-broker-2
      - kafka-broker-3
      - apicurio
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-broker-1:9092,kafka-broker-2:9092,kafka-broker-3:9092
  debezium:
    image: debezium/connect:3.0
    platform: linux/amd64
    container_name: debezium
    depends_on:
      - kafka-broker-1
      - kafka-broker-2
      - kafka-broker-3
      - apicurio
      - postgres
    ports:
      - "8083:8083"
    environment:
      # https://debezium.io/documentation/reference/stable/configuration/avro.html#deploying-with-debezium-containers
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: "connect-config"
      OFFSET_STORAGE_TOPIC: "connect-offsets"
      STATUS_STORAGE_TOPIC: "connect-status"
      BOOTSTRAP_SERVERS: kafka-broker-1:9092,kafka-broker-2:9092,kafka-broker-3:9092
      LOGGING_LEVEL: "DEBUG"
      CONNECT_SCHEMA_NAME_ADJUSTMENT_MODE: avro
      ENABLE_APICURIO_CONVERTERS: "true"
      KEY_CONVERTER: io.apicurio.registry.utils.converter.AvroConverter
      VALUE_CONVERTER: io.apicurio.registry.utils.converter.AvroConverter
      CONNECT_KEY_CONVERTER: io.apicurio.registry.utils.converter.AvroConverter
      CONNECT_VALUE_CONVERTER: io.apicurio.registry.utils.converter.AvroConverter
      CONNECT_KEY_CONVERTER_APICURIO_REGISTRY_URL: http://apicurio:8080/apis/registry/v2
      CONNECT_VALUE_CONVERTER_APICURIO_REGISTRY_URL: http://apicurio:8080/apis/registry/v2
      CONNECT_VALUE_CONVERTER_APICURIO_REGISTRY_AUTO-REGISTER: "true"
      CONNECT_VALUE_CONVERTER_APICURIO_REGISTRY_FIND-LATEST: "true"
      CONNECT_KEY_CONVERTER_APICURIO_REGISTRY_AUTO-REGISTER: "true"
      CONNECT_KEY_CONVERTER_APICURIO_REGISTRY_FIND-LATEST: "true"
  apicurio:
    image: apicurio/apicurio-registry:latest-release
    platform: linux/amd64
    container_name: apicurio
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    environment:
      # https://github.com/Apicurio/apicurio-registry/blob/main/examples/event-driven-architecture/README.md
      APICURIO_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      APICURIO_DATASOURCE_USERNAME: user
      APICURIO_DATASOURCE_PASSWORD: admin
      APICURIO_STORAGE_KIND: "sql"
      APICURIO_STORAGE_SQL_KIND: "postgresql"
  redis:
    image: redis:7.2
    platform: linux/amd64
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: admin