
server:
  port: ${PORT:8181}

logging:
  level:
    org:
      springframework: ${LOGGING_LEVEL:INFO}

spring:
  application:
    name: order-service-command
  jpa:
    open-in-view: false

spring.datasource:
  url: jdbc:postgresql://${DATABASE_HOST:localhost}:5432/postgres?stringtype=unspecified&currentSchema=order_command
  username: ${DATABASE_USER:user}
  password: ${DATABASE_PASSWORD:admin}
  driver-class-name: org.postgresql.Driver

spring.sql:
  init:
    schema-locations: classpath:init-schema.sql
    platform: postgres
    mode: always

spring.security:
  oauth2:
    resourceserver:
      jwt:
        jwk-set-uri: ${JWK_SET_URI:http://localhost:9090/realms/food-delivery-app/protocol/openid-connect/certs}